services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    hostname: openspeedtest
    restart: unless-stopped
    environment:
      HTTP_PORT: ${HTTP_PORT:-3000}
      HTTPS_PORT: ${HTTPS_PORT:-3001}
    networks:
      net:
        ipv4_address: ${APP_IP}
    dns:
      - ${DNS_IP_1}
      - ${DNS_IP_2:-9.9.9.9}

networks:
  net:
    external: true
    name: webapps-network