services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    hostname: openspeedtest
    restart: unless-stopped
    ports:
        - '${HTTP_PORT:-80}:3000'
        - '${HTTPS_PORT:-443}:3001'
    networks:
      net:
        ipv4_address: ${APP_IP}
    dns:
      - ${DNS_IP_1}
      - ${DNS_IP_2:-9.9.9.9}

networks:
  net:
    external: true
    name: webapps-network